version: "3.9"
services:
  application:
        build: .
        ports:
          - "8080:8080"
        depends_on:
          - "postgres_db"
  postgres_db:
        image: "postgres:14"
        ports:
          - "5432:5432"
        environment:
          POSTGRES_PASSWORD: qwerty
